### ISSUE TITLE
14강 4번 

### ISSUE THREAD

**Issue by goodbeing1231** [seoulrain/studyhacks#203]
Standards are prevalent in our modern world because they reduce the costs of interactions among the firms and people that subscribe to them. Hence, it is not unexpected to see standards coevolve with markets. Many people are surprised to learn that only a few centuries ago simple measures of weight and volume, such as the pound and the pint,  were not standard. Even though the same word was used in different towns, the weight of a pound varied from town to town — sometimes by as much as a factor of four. But as cities began to trade with one another and governments began to impose their rule over larger areas, the use of standards grew.  The coevolution of standards and markets is easy to understand, since anyone buying a bushel of corn from a vendor in another town would want that bushel to mean the same in both towns. So the possibility of trade created an incentive for standardization, and helped the **expansion** of the governments that were keen on the use of standards.

마지막 줄 "expansion"이 정부의 수가 늘어나는 걸 뜻한다고 하셨는데, 규모가 아니라 수인 근거가 뭐에요? 
표준을 사용함으로써 여러 마을들이 하나로 통합되고 중앙집권화되는 것 - 규모가 커지거나 힘이 세지는 것으로 해석할 수는 없나요?

**Comment by seoulrain** [comment]
Standards are prevalent in our modern world because they reduce the costs of interactions among the firms and people that subscribe to them. Hence, it is not unexpected to see standards coevolve with markets. Many people are surprised to learn that only a few centuries ago simple measures of weight and volume, such as the pound and the pint, were not standard. Even though the same word was used in different towns, the weight of a pound varied from town to town — sometimes by as much as a factor of four. But as cities began to trade with one another and governments began to impose their rule over larger areas, the use of standards grew. The coevolution of standards and markets is easy to understand, since anyone buying a bushel of corn from a vendor in another town would want that bushel to mean the same in both towns. So the possibility of trade created an incentive for standardization, and helped the expansion of the governments that were keen on the use of standards.

> 마지막 줄 "expansion"이 정부의 수가 늘어나는 걸 뜻한다고 하셨는데, 규모가 아니라 수인 근거가 뭐에요?
> 표준을 사용함으로써 여러 마을들이 하나로 통합되고 중앙집권화되는 것 - 규모가 커지거나 힘이 세지는 것으로 해석할 수는 없나요?

-- 음... "But as cities began to trade with one another and governments began to impose their rule over larger areas, the use of standards grew." 이라고 위에서 말했으니 정부가 교역의 확대에 따라서 더 넓은 지역에 규칙을 적용하고 싶다고 했으니 교역이 결국 표준의 적용 범위의 확대라고 해석해도 안 될 건 없을 거 같은데.. 
-- helped the expansion of the governments that were keen on the use of standard .. 라고 쓴 마지막 문장의 부분에서 표준 사용을 원하는 정부가 확대된다고 해서 그 크기인지 범위인지 좀 명확하지는 않은 듯. 하지만 표준사용을 원하는 정부들이 더욱 많아졌다(in number)라는 해석이 결국 표준 사용 범위의 확대(in size, over larger areas)와 다른 말도 아닌 듯! 
-- 마지막 문장 '양'으로 읽어도 됩니다.
